# Generated by Django 4.2.5 on 2023-10-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_clients_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
