# Generated by Django 4.2.5 on 2023-10-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
