# Generated by Django 4.2.5 on 2023-10-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_client_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='updated_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
