# Generated by Django 4.2.5 on 2023-09-30 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_clients_date_cad_remove_clients_date_del_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clients',
            new_name='Client',
        ),
    ]
