# Generated by Django 4.2.5 on 2023-10-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_client_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
