# Generated by Django 4.2.5 on 2023-10-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_alter_client_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
