# Generated by Django 4.2.5 on 2023-09-30 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('number', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(max_length=30, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_reserved', models.BooleanField(default=False)),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_clean', models.BooleanField(default=True)),
                ('is_broken', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(max_length=30, null=True)),
                ('updated_by', models.CharField(max_length=30, null=True)),
                ('deleted_by', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair_number', models.IntegerField(null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('type', models.CharField(max_length=30, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.table')),
            ],
        ),
    ]
