# Generated by Django 4.2.5 on 2023-09-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_table_number_chairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='qr_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
