# Generated by Django 4.2.5 on 2023-10-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_menu_deleted_by_alter_menu_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='created_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
