# Generated by Django 4.2.6 on 2023-12-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_menu_vegan_menu_vegetarian_alter_menu_allergen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
