# Generated by Django 4.2.5 on 2023-09-30 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu_allergenes',
            new_name='Menu_allergene',
        ),
        migrations.RenameModel(
            old_name='Menu_ingredients',
            new_name='Menu_ingredient',
        ),
    ]
