# Generated by Django 4.2.5 on 2023-09-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_menu_allergenes_menu_allergene_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='allergen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='gluten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='lactose',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Menu_allergene',
        ),
    ]
