# Generated by Django 4.2.5 on 2023-09-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menu_allergens'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='ingredients',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Menu_ingredient',
        ),
    ]
