# Generated by Django 4.2.5 on 2023-10-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menu_nutrition_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='nutrition_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
