# Generated by Django 4.2.5 on 2023-09-30 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_seat_description_seat_qr_code'),
        ('orders', '0002_remove_order_menu_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tables.seat'),
            preserve_default=False,
        ),
    ]
